name: qr-code-deploy

on:
  push:
    branches:
      - main # Set a branch to deploy
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: davidgs/web-qr
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          path: ./web-qr
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn
      - run: yarn build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          path: ./web-qr/build/
          remote_path: /var/www/vhosts/qr-builder.io/httpdocs
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.WEBSITE_DEPLOY_KEY }}
